use es6 for awesome book
bhushan354/Awesome-Book-Es6 pull request #1
Opened 2023-08-14 11:19 UTC by bhushan354

In this pull request I have used ES6 version of JS to build this awesomeBook project

2023-08-14 19:21 UTC, Olamarx requested changes
Hi @bhushan354, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Good commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-14 19:21 UTC, Olamarx commented on index.js
> +function Form() {
- [ ] I will encourage you to change all functions to the arrow function so that it would help javascript in the runtime and avoid hoisting.

2023-08-14 19:21 UTC, Olamarx commented on index.js
> +}, 1000);
- [ ] I noticed only time is being displayed, kindly display the date too
![image](https://github.com/bhushan354/Awesome-Book-Es6/assets/86200356/b7e49fbf-ac29-4b58-b6f6-23b6f346c11e)

2023-08-15 01:06 UTC, bhushan354 commented
Hello sir , thank you reviewing my code , I have made changes suggestedby previous reviewer :

- Made all functions as arrow function .
- Also I think the previous reviewer checked the wrong commit because i don't have any background image in my directory and time and date was showing .
![Screenshot from 2023-08-15 06-09-57](https://github.com/bhushan354/Awesome-Book-Es6/assets/127464886/c9b6bf7b-2630-4543-8fb9-c5b235c343e8)

Thank you ,
Bhushan .

2023-08-15 01:29 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @bhushan354,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-08-19 09:18 UTC, merged